name: task runner

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '00 13 * * *'
# 1300 hours UTC Should mean 6 am Pacific

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.15
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.15
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the task
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PRIVATE_API_KEY_AIRTABLE: ${{ secrets.PRIVATE_API_KEY_AIRTABLE }}
          PRIVATE_BASE_KEY: ${{ secrets.PRIVATE_BASE_KEY }}
          PRIVATE_TABLE_NAME_SERVICEDUMP: ${{ secrets.PRIVATE_TABLE_NAME_SERVICEDUMP }}
        run: |
          python task.py
      - uses: gautamkrishnar/keepalive-workflow@master
